name: nex
channels:
  #- defaults
  #- conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - python=3.8
  - ffmpeg=4.2.2
  - numpy=1.18.1
  - pandas=1.0.3
  - pip
  - scikit-image=0.16.2
  - imageio=2.9.0
  - scipy=1.4.1
  - pip:
    - opencv-python==4.1.2.30
    - lpips==0.1.3
    - tensorboard==2.4.1
    # - torch==1.8.1+cu111
    # - torchvision==0.9.1+cu111
    - tqdm==4.59.0
